#!/bin/sh

echo "# File @generated by generate-authors.sh. DO NOT EDIT." > AUTHORS
echo "# This file lists all contributors to the repository." >> AUTHORS
echo " " >> AUTHORS

git shortlog -se \
  | perl -spe 's/^\s+\d+\s+//' \
  | sed -e '/^CommitSyncScript.*$/d' \
  >> AUTHORS
